from mysql.connector import connect, Error

class userDB:

    def __init__(self):

        with open("config_sql", "r") as file:
            configs = file.readlines()
            file.close()
        with open("sqlpassword", "r") as file:
            sqlpassword = file.read().strip()
            file.close()

        #self.connection = connect(host=str(configs[0]).strip(), user=str(configs[1]).strip(), password=sqlpassword, database="userinfotest")
        self.connection = connect(host='54.78.230.206', user='root', password='my_secret_password', database="userinfotest")
        self.cursor = self.connection.cursor()

    def close_down(self):
        self.cursor.close()
        self.connection.close()
        pass


class ProjectDB(userDB):
    def __init__(self):

        with open("config_sql", "r") as file:
            configs = file.readlines()
            file.close()
        with open("sqlpassword", "r") as file:
            sqlpassword = file.read().strip()
            file.close()

        #self.connection = connect(host=str(configs[0]).strip(), user=str(configs[1]).strip(), password=sqlpassword, database="projects")
        self.connection = connect(host='54.78.230.206', user='root', password='my_secret_password', database='projects')
        self.cursor = self.connection.cursor()

class CVEDB(userDB):
    def __init__(self):

        with open("config_sql", "r") as file:
            configs = file.readlines()
            file.close()
        with open("sqlpassword", "r") as file:
            sqlpassword = file.read().strip()
            file.close()

        #self.connection = connect(host=str(configs[0]).strip(), user=str(configs[1]).strip(), password=sqlpassword, database="cve_data")
        self.connection = connect(host='54.78.230.206', user='root', password='my_secret_password', database='cve_data')
        self.cursor = self.connection.cursor()
